Menu Navegação do Site
murilopita/xbox-clone-page pull request #1
Opened 2022-09-29 22:35 UTC by murilopita

Fiz o menu Navegação do Site.

2022-10-02 04:37 UTC, darlancostadev requested changes

2022-10-02 04:37 UTC, darlancostadev commented on style.css
> +header nav .navbar2 ul{
Aqui você pode aplicar seu estilo sem chamar as tags dês do inicio abstrair o **header** e **nav**, por exemplo 
```
.navbar2 ul {
  styles
}
```
O .navbar2 se torna uma chave class de identificação!
Assim também com os outros acima e abaixo!

2022-10-02 04:37 UTC, darlancostadev commented on index.html
> +                    <li><a href="#">Pesquisar<img id="icons" src="assets/icons/search.png" alt="Pesquisar"></a></li>
Seguindo as boas praticas de escrita em HMTL e CSS o **id** deve ser único você poderia trocar o `id="icons"` por uma class já que ele se repete nas tags abaixo e tem o mesmo estilo

2022-10-02 04:37 UTC, darlancostadev commented on style.css
> +
Aqui no #icon e #login-icon como mencionei acima pode ser usado como uma class.

2022-10-02 04:37 UTC, darlancostadev commented on index.html
>              <div class="navbar1">
Entendo que aqui podemos trabalhar com um nome mais intuitivo não acho um boa pratica escrever números para referenciar uma class ou id podemos trocar para `#navbar-left e #navbar-right` assim qualquer pessoa que for trabalhar no seu código só de olhar entende o estilo mesmo sem ter visto o site!

2022-10-02 04:40 UTC, darlancostadev commented on style.css
> +
Podemos também trabalhar melhor essa apresentação do **Pull Request** gosto bastante de um print da tela evidenciando que você obteve sucesso ao desenvolver a tarefa, pode usar uma imagem ou gif e adicionar no campo descrição do **PR**

2022-10-04 23:59 UTC, murilopita commented on style.css
> +
Vou aplicar nos próximos PR's

2022-10-05 00:33 UTC, darlancostadev commented on style.css
> +/* Navbar Left */
Pode remover esses comentários o nome da class já é bem explicativa!

2022-10-05 00:37 UTC, darlancostadev commented on style.css
> +html, body, ul, a{
Um a boa pratica é remover esse reset do css em um arquivo separado e importar ele sempre que precisar evitando assim precisar reescrever o codigo em cada arquivo que existir
exemplo:
style/reset.css
style/desktop.css
style/mobile.css

em desktop e mobile vc pode importar o reset.css sem reescrever código já que ambos precisam de um reset!

2022-10-23 17:07 UTC, darlancostadev approved these changes

2022-10-24 19:48 UTC, merged